CREATE TABLE MEMBER ( 
   PID INT NOT NULL, 
   MEMBER_ID VARCHAR(50) NOT NULL, 
   FIRST_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50) NOT NULL,
   BIRTH_DATE DATE
);


CREATE TABLE USER_INFO (
	ID LONG NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE APP_PROPERTIES (
	ID LONG NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL
);

INSERT INTO MEMBER VALUES (1, 'ecronin', 'Ernest', 'Cronin', '1980-05-06');
INSERT INTO MEMBER VALUES (2, 'scronin', 'Sandy', 'Cronin', '1991-01-19');

INSERT INTO USER_INFO VALUES(1, 'sa@h2.com', 'password', 'ADMIN');
INSERT INTO USER_INFO VALUES(2, 'ecronin@medecision.com', '$2a$12$cmHRKbf3kKlg3Uf5JJQp7uUQEttgbWR6d2mROjIPuVHojv2OljzIC', 'ADMIN');

INSERT INTO APP_PROPERTIES VALUES(1, 'MEMBER_SERVICES', 'secret');